#!/usr/bin/env python3

ANIONS2SEARCH=["O","S","Se","Te","F","Cl","Br","I"]
#ANIONS2DECORATE=["O"]
ANIONS2DECORATE=["O", "I", "S"]
CATIONS2DECORATE=["Li","Na","K","Mg","Ca","Ti","V","Cr","Mn","Fe","Co","Ni","Cu","Zn","Tc"]
NARY=4  #JAG LOOK HERE, CAN YOU FIX FOR NARY=3 WITH BOTH MULTI-CATION AND MULTI-ANION FORCING "O" TO ALWAYS BE PRESENT ?
PERFORM_COMPARISONS=False
